# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crossed_selection_dialog_base.ui'
#
# Created: Tue May 12 03:51:04 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CrossedSelectionDialogBase(object):
    def setupUi(self, CrossedSelectionDialogBase):
        CrossedSelectionDialogBase.setObjectName(_fromUtf8("CrossedSelectionDialogBase"))
        CrossedSelectionDialogBase.setWindowModality(QtCore.Qt.NonModal)
        CrossedSelectionDialogBase.resize(443, 508)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CrossedSelectionDialogBase.sizePolicy().hasHeightForWidth())
        CrossedSelectionDialogBase.setSizePolicy(sizePolicy)
        CrossedSelectionDialogBase.setModal(True)
        self.button_box = QtGui.QDialogButtonBox(CrossedSelectionDialogBase)
        self.button_box.setGeometry(QtCore.QRect(250, 430, 171, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.layoutWidget = QtGui.QWidget(CrossedSelectionDialogBase)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 174, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.srcLayer = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcLayer.sizePolicy().hasHeightForWidth())
        self.srcLayer.setSizePolicy(sizePolicy)
        self.srcLayer.setMinimumSize(QtCore.QSize(0, 23))
        self.srcLayer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srcLayer.setSizeIncrement(QtCore.QSize(0, 0))
        self.srcLayer.setWhatsThis(_fromUtf8(""))
        self.srcLayer.setObjectName(_fromUtf8("srcLayer"))
        self.horizontalLayout_2.addWidget(self.srcLayer)
        self.layoutWidget_3 = QtGui.QWidget(CrossedSelectionDialogBase)
        self.layoutWidget_3.setGeometry(QtCore.QRect(250, 30, 174, 25))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.tgtLayer = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgtLayer.sizePolicy().hasHeightForWidth())
        self.tgtLayer.setSizePolicy(sizePolicy)
        self.tgtLayer.setMinimumSize(QtCore.QSize(0, 23))
        self.tgtLayer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tgtLayer.setSizeIncrement(QtCore.QSize(0, 0))
        self.tgtLayer.setWhatsThis(_fromUtf8(""))
        self.tgtLayer.setObjectName(_fromUtf8("tgtLayer"))
        self.horizontalLayout_4.addWidget(self.tgtLayer)
        self.layoutWidget_4 = QtGui.QWidget(CrossedSelectionDialogBase)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 70, 391, 25))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.srcField = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcField.sizePolicy().hasHeightForWidth())
        self.srcField.setSizePolicy(sizePolicy)
        self.srcField.setMinimumSize(QtCore.QSize(0, 23))
        self.srcField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srcField.setSizeIncrement(QtCore.QSize(0, 0))
        self.srcField.setWhatsThis(_fromUtf8(""))
        self.srcField.setObjectName(_fromUtf8("srcField"))
        self.horizontalLayout_5.addWidget(self.srcField)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tgtField = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgtField.sizePolicy().hasHeightForWidth())
        self.tgtField.setSizePolicy(sizePolicy)
        self.tgtField.setMinimumSize(QtCore.QSize(0, 23))
        self.tgtField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tgtField.setSizeIncrement(QtCore.QSize(0, 0))
        self.tgtField.setWhatsThis(_fromUtf8(""))
        self.tgtField.setObjectName(_fromUtf8("tgtField"))
        self.horizontalLayout_5.addWidget(self.tgtField)
        self.progressbar = QtGui.QProgressBar(CrossedSelectionDialogBase)
        self.progressbar.setGeometry(QtCore.QRect(30, 470, 391, 20))
        self.progressbar.setProperty("value", 0)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.chk_SrcLayer = QtGui.QCheckBox(CrossedSelectionDialogBase)
        self.chk_SrcLayer.setGeometry(QtCore.QRect(30, 100, 171, 17))
        self.chk_SrcLayer.setObjectName(_fromUtf8("chk_SrcLayer"))
        self.chk_TgtLayer = QtGui.QCheckBox(CrossedSelectionDialogBase)
        self.chk_TgtLayer.setGeometry(QtCore.QRect(250, 100, 171, 17))
        self.chk_TgtLayer.setObjectName(_fromUtf8("chk_TgtLayer"))
        self.advancedBox = QtGui.QGroupBox(CrossedSelectionDialogBase)
        self.advancedBox.setGeometry(QtCore.QRect(30, 130, 391, 291))
        self.advancedBox.setCheckable(True)
        self.advancedBox.setChecked(False)
        self.advancedBox.setObjectName(_fromUtf8("advancedBox"))
        self.layoutWidget_5 = QtGui.QWidget(self.advancedBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 20, 201, 25))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.fltField = QtGui.QComboBox(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fltField.sizePolicy().hasHeightForWidth())
        self.fltField.setSizePolicy(sizePolicy)
        self.fltField.setMinimumSize(QtCore.QSize(0, 23))
        self.fltField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fltField.setSizeIncrement(QtCore.QSize(0, 0))
        self.fltField.setWhatsThis(_fromUtf8(""))
        self.fltField.setObjectName(_fromUtf8("fltField"))
        self.horizontalLayout_6.addWidget(self.fltField)
        self.valuesList = QtGui.QListWidget(self.advancedBox)
        self.valuesList.setGeometry(QtCore.QRect(10, 60, 371, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valuesList.sizePolicy().hasHeightForWidth())
        self.valuesList.setSizePolicy(sizePolicy)
        self.valuesList.setSizeIncrement(QtCore.QSize(0, 0))
        self.valuesList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.valuesList.setMouseTracking(False)
        self.valuesList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.valuesList.setWhatsThis(_fromUtf8(""))
        self.valuesList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.valuesList.setAlternatingRowColors(True)
        self.valuesList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.valuesList.setResizeMode(QtGui.QListView.Fixed)
        self.valuesList.setObjectName(_fromUtf8("valuesList"))

        self.retranslateUi(CrossedSelectionDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), CrossedSelectionDialogBase.reject)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), CrossedSelectionDialogBase.accept)
        QtCore.QMetaObject.connectSlotsByName(CrossedSelectionDialogBase)

    def retranslateUi(self, CrossedSelectionDialogBase):
        CrossedSelectionDialogBase.setWindowTitle(_translate("CrossedSelectionDialogBase", "Crossed Selection", None))
        self.label.setText(_translate("CrossedSelectionDialogBase", "Source Layer", None))
        self.srcLayer.setToolTip(_translate("CrossedSelectionDialogBase", "Choose the output file format", None))
        self.label_3.setText(_translate("CrossedSelectionDialogBase", "Target Layer", None))
        self.tgtLayer.setToolTip(_translate("CrossedSelectionDialogBase", "Layer to select features from", None))
        self.srcField.setToolTip(_translate("CrossedSelectionDialogBase", "Choose the field in which to select attribute values", None))
        self.label_4.setText(_translate("CrossedSelectionDialogBase", "<html><head/><body><p>&lt;-- Relational Fields --&gt;</p></body></html>", None))
        self.tgtField.setToolTip(_translate("CrossedSelectionDialogBase", "Choose the field in which to check attribute values", None))
        self.chk_SrcLayer.setText(_translate("CrossedSelectionDialogBase", "Use selected features only", None))
        self.chk_TgtLayer.setText(_translate("CrossedSelectionDialogBase", "Use selected features only", None))
        self.advancedBox.setTitle(_translate("CrossedSelectionDialogBase", "Advanced parameters", None))
        self.label_5.setText(_translate("CrossedSelectionDialogBase", "Filter by field", None))
        self.fltField.setToolTip(_translate("CrossedSelectionDialogBase", "Choose the field in which to select attribute values", None))
        self.valuesList.setToolTip(_translate("CrossedSelectionDialogBase", "Show unique values of selected field", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CrossedSelectionDialogBase = QtGui.QDialog()
    ui = Ui_CrossedSelectionDialogBase()
    ui.setupUi(CrossedSelectionDialogBase)
    CrossedSelectionDialogBase.show()
    sys.exit(app.exec_())

